In [7]:
"""majority_circuit.ipynb"""
# cell 1


# All these cells were created using chatgpt
import numpy as np

def majority_gate(a, b, c):
    # Calculate the majority output based on the inputs
    return int(a + b + c >= 2)

def generate_majority_circuit_arrays():
    # Input states (A, B, C)
    inputs = np.array([(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)])

    # Output states
    outputs = []

    # Calculate the output state for each input permutation
    for a, b, c in inputs:
        output = majority_gate(a, b, c)
        outputs.append(output)

    # Logic gate matrices
    not_gate = np.array([[0, 1], [1, 0]])
    and_gate = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 1]])
    or_gate = np.array([[0, 1, 1], [1, 1, 1], [1, 1, 1]])

    print("Input states (A, B, C):")
    print(inputs)
    print("\nOutput states:")
    print(outputs)
    print("\nNOT Gate Matrix:")
    print(not_gate)
    print("\nAND Gate Matrix:")
    print(and_gate)
    print("\nOR Gate Matrix:")
    print(or_gate)

if __name__ == "__main__":
    generate_majority_circuit_arrays()


Input states (A, B, C):
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]

Output states:
[0, 0, 0, 1, 0, 1, 1, 1]

NOT Gate Matrix:
[[0 1]
 [1 0]]

AND Gate Matrix:
[[0 0 0]
 [0 1 0]
 [0 0 1]]

OR Gate Matrix:
[[0 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
"""majority_circuit.ipynb"""
# cell 2


def not_gate(a):
    # NOT gate logic
    return int(not a)

def and_gate(a, b):
    # AND gate logic
    return int(a and b)

def or_gate(a, b):
    # OR gate logic
    return int(a or b)

def majority_gate(a, b, c):
    # Calculate the majority output based on the inputs
    return int(a + b + c >= 2)

def logic_circuit(inputs):
    # Logic gate matrices
    not_gate_matrix = np.vectorize(not_gate)
    and_gate_matrix = np.vectorize(and_gate)
    or_gate_matrix = np.vectorize(or_gate)

    # Calculate NOT(A), NOT(B), and NOT(C)
    not_a = not_gate_matrix(inputs[:, 0])
    not_b = not_gate_matrix(inputs[:, 1])
    not_c = not_gate_matrix(inputs[:, 2])

    # Calculate (NOT(A) AND B AND C), (A AND NOT(B) AND C), and (A AND B AND NOT(C))
    and1_output = and_gate_matrix(not_a, inputs[:, 1]) * inputs[:, 2]
    and2_output = and_gate_matrix(inputs[:, 0], not_b) * inputs[:, 2]
    and3_output = and_gate_matrix(inputs[:, 0], inputs[:, 1]) * not_c

    # Calculate the majority output
    majority_output = np.vectorize(majority_gate)(and1_output, and2_output, and3_output)

    # Calculate (A OR B OR C)
    or_output = or_gate_matrix(or_gate_matrix(inputs[:, 0], inputs[:, 1]), inputs[:, 2])

    # Final output (Majority AND (A OR B OR C))
    output = np.vectorize(majority_gate)(majority_output, or_output, 0)

    return output

def majority_gate(a, b, c):
    # Calculate the majority output based on the inputs
    return int(a + b + c >= 2)


In [13]:
"""majority_circuit.ipynb"""
# cell 3


def generate_truth_table():
    # Input states (A, B, C)
    inputs = np.array([(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)])

    # Output states
    outputs = []

    # Calculate the output state for each input permutation
    for a, b, c in inputs:
        output = majority_gate(a, b, c)
        outputs.append(output)

    # Display the truth table
    print("Truth Table:")
    print("Input (A, B, C) | Output")
    print("-------------------------")
    for i in range(len(inputs)):
        input_state = " ".join(str(bit) for bit in inputs[i])
        output_state = outputs[i]
        print(f"     {input_state}       |   {output_state}")

if __name__ == "__main__":
    generate_truth_table()

Truth Table:
Input (A, B, C) | Output
-------------------------
     0 0 0       |   0
     0 0 1       |   0
     0 1 0       |   0
     0 1 1       |   1
     1 0 0       |   0
     1 0 1       |   1
     1 1 0       |   1
     1 1 1       |   1
